/*----- PROTECTED REGION ID(WagoInterlockStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: WagoInterlockStateMachine.cpp,v 1.1.1.1 2013-07-15 08:18:19 kowalisz Exp $";
//=============================================================================
//
// file :        WagoInterlockStateMachine.cpp
//
// description : State machine file for the WagoInterlock class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author: kowalisz $
//
// $Revision: 1.1.1.1 $
// $Date: 2013-07-15 08:18:19 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <WagoInterlock.h>

/*----- PROTECTED REGION END -----*/	//	WagoInterlock::WagoInterlockStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  
//  FAULT    |  
//  ALARM    |  
//  UNKNOWN  |  


namespace WagoInterlock_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : WagoInterlock::is_UploadConfig_allowed()
 * Description:  Execution allowed for UploadConfig attribute
 */
//--------------------------------------------------------
bool WagoInterlock::is_UploadConfig_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for UploadConfig command.
	/*----- PROTECTED REGION ID(WagoInterlock::UploadConfigStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	WagoInterlock::UploadConfigStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : WagoInterlock::is_Reset_allowed()
 * Description:  Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool WagoInterlock::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Reset command.
	/*----- PROTECTED REGION ID(WagoInterlock::ResetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	WagoInterlock::ResetStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(WagoInterlock::WagoInterlockStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	WagoInterlock::WagoInterlockStateAllowed.AdditionalMethods

}	//	End of namespace
